name: pre-release

on: workflow_dispatch

jobs:

  measures_common:
    uses: ./.github/workflows/measures_common.yaml

  measures_gbxml:
    uses: ./.github/workflows/measures_gbxml.yaml

  measures_systems:
    uses: ./.github/workflows/measures_systems.yaml

  upload:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - uses: actions/upload-artifact@v3
      with:
        name: measures
        path: measures

  download:
    runs-on: windows-2019
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: measures
